name: My First Pipeline

on:
  push:

jobs:

  hello-job:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Say hello
        run: echo "Hello CI!"
